DancingGoat/Models/AboutUsViewModel.cs
using System.Collections.Generic;

namespace DancingGoat.Models
{
    public class AboutUsViewModel : AboutUs
    {
        public string ItemId { get; set; }
        public string Language { get; set; }
        public IList<FactAboutUsViewModel> FactViewModels { get; set; }
    }
}

DancingGoat/Models/CafesViewModel.cs
using System.Collections.Generic;

namespace DancingGoat.Models
{
    public class CafesViewModel
    {
        public List<Cafe> CompanyCafes { get; set; }

        public List<Cafe> PartnerCafes { get; set; }
    }
}

DancingGoat/Models/ContentTypes/AboutUs.cs
// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace DancingGoat.Models
{
    public partial class AboutUs
    {
        public const string Codename = "about_us";
        public const string OurMottoCodename = "our_motto";
        public const string VideoCodename = "video";
        public const string MetadataOgDescriptionCodename = "metadata__og_description";
        public const string MetadataMetaTitleCodename = "metadata__meta_title";
        public const string MetadataOgTitleCodename = "metadata__og_title";
        public const string MetadataMetaDescriptionCodename = "metadata__meta_description";
        public const string MetadataTwitterSiteCodename = "metadata__twitter_site";
        public const string UrlPatternCodename = "url_pattern";
        public const string MetadataTwitterImageCodename = "metadata__twitter_image";
        public const string MetadataTwitterCreatorCodename = "metadata__twitter_creator";
        public const string MetadataTwitterTitleCodename = "metadata__twitter_title";
        public const string MetadataTwitterDescriptionCodename = "metadata__twitter_description";
        public const string MetadataOgImageCodename = "metadata__og_image";
        public const string FactsCodename = "facts";

        public string OurMotto { get; set; }
        public IEnumerable<HostedVideo> Video { get; set; }
        public string MetadataOgDescription { get; set; }
        public string MetadataMetaTitle { get; set; }
        public string MetadataOgTitle { get; set; }
        public string MetadataMetaDescription { get; set; }
        public string MetadataTwitterSite { get; set; }
        public string UrlPattern { get; set; }
        public IEnumerable<Asset> MetadataTwitterImage { get; set; }
        public string MetadataTwitterCreator { get; set; }
        public string MetadataTwitterTitle { get; set; }
        public string MetadataTwitterDescription { get; set; }
        public IEnumerable<Asset> MetadataOgImage { get; set; }
        public IEnumerable<object> Facts { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}

DancingGoat/Models/ContentTypes/Article.cs
// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace DancingGoat.Models
{
    public partial class Article
    {
        public const string Codename = "article";
        public const string MetadataOgDescriptionCodename = "metadata__og_description";
        public const string MetadataMetaTitleCodename = "metadata__meta_title";
        public const string PersonasCodename = "personas";
        public const string BodyCopyCodename = "body_copy";
        public const string MetadataOgTitleCodename = "metadata__og_title";
        public const string MetadataMetaDescriptionCodename = "metadata__meta_description";
        public const string MetadataTwitterSiteCodename = "metadata__twitter_site";
        public const string PostDateCodename = "post_date";
        public const string MetaKeywordsCodename = "meta_keywords";
        public const string TeaserImageCodename = "teaser_image";
        public const string MetadataTwitterImageCodename = "metadata__twitter_image";
        public const string MetadataTwitterCreatorCodename = "metadata__twitter_creator";
        public const string TitleCodename = "title";
        public const string SummaryCodename = "summary";
        public const string MetadataTwitterTitleCodename = "metadata__twitter_title";
        public const string MetadataTwitterDescriptionCodename = "metadata__twitter_description";
        public const string MetaDescriptionCodename = "meta_description";
        public const string MetadataOgImageCodename = "metadata__og_image";
        public const string RelatedArticlesCodename = "related_articles";
        public const string UrlPatternCodename = "url_pattern";

        public string MetadataOgDescription { get; set; }
        public string MetadataMetaTitle { get; set; }
        public IEnumerable<TaxonomyTerm> Personas { get; set; }
        public IRichTextContent BodyCopy { get; set; }
        public string MetadataOgTitle { get; set; }
        public string MetadataMetaDescription { get; set; }
        public string MetadataTwitterSite { get; set; }
        public DateTime? PostDate { get; set; }
        public string MetaKeywords { get; set; }
        public IEnumerable<Asset> TeaserImage { get; set; }
        public IEnumerable<Asset> MetadataTwitterImage { get; set; }
        public string MetadataTwitterCreator { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string MetadataTwitterTitle { get; set; }
        public string MetadataTwitterDescription { get; set; }
        public string MetaDescription { get; set; }
        public IEnumerable<Asset> MetadataOgImage { get; set; }
        public IEnumerable<object> RelatedArticles { get; set; }
        public string UrlPattern { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}

DancingGoat/Models/ContentTypes/Cafe.cs
// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace DancingGoat.Models
{
    public partial class Cafe
    {
        public const string Codename = "cafe";
        public const string PhoneCodename = "phone";
        public const string CityCodename = "city";
        public const string PhotoCodename = "photo";
        public const string EmailCodename = "email";
        public const string CountryCodename = "country";
        public const string StreetCodename = "street";
        public const string StateCodename = "state";
        public const string ZipCodeCodename = "zip_code";

        public string Phone { get; set; }
        public string City { get; set; }
        public IEnumerable<Asset> Photo { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string Street { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}

DancingGoat/Models/ContentTypes/FactAboutUs.cs
// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace DancingGoat.Models
{
    public partial class FactAboutUs
    {
        public const string Codename = "fact_about_us";
        public const string DescriptionCodename = "description";
        public const string TitleCodename = "title";
        public const string ImageCodename = "image";

        public IRichTextContent Description { get; set; }
        public string Title { get; set; }
        public IEnumerable<Asset> Image { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}

DancingGoat/Models/ContentTypes/HostedVideo.cs
// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery;

namespace DancingGoat.Models
{
    public partial class HostedVideo
    {
        public const string Codename = "hosted_video";
        public const string VideoIdCodename = "video_id";
        public const string VideoHostCodename = "video_host";

        public string VideoId { get; set; }
        public IEnumerable<MultipleChoiceOption> VideoHost { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}

DancingGoat/Models/ContentTypesWithMetadata/AboutUs.cs
namespace DancingGoat.Models
{
    public partial class AboutUs: IMetadata
    {
    }
}

DancingGoat/Models/ContentTypesWithMetadata/Article.cs
namespace DancingGoat.Models
{
    public partial class Article: IMetadata, IDetailItem
    {
        public string Type => System.Type;
        public string Id => System.Id;
    }
}

DancingGoat/Models/FactAboutUsViewModel.cs
using KenticoCloud.ContentManagement.Helpers.Models;

namespace DancingGoat.Models
{
    public class FactAboutUsViewModel
    {
        public FactAboutUs Fact { get; set; }
        public bool Odd { get; set; }
        public ElementIdentifier ParentItemElementIdentifier { get; set; }
    }
}

DancingGoat/Controllers/ArticlesController.cs
using DancingGoat.Models;
using Kentico.Kontent.Delivery;
using Kentico.Kontent.Recommender;
using System;
using System.Configuration;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DancingGoat.Controllers
{
    public class ArticlesController : ControllerBase
    {
        public async Task<ActionResult> Index()
        {
            var response = await client.GetItemsAsync<Article>(
                new EqualsFilter("system.type", "article"),
                new OrderParameter("elements.post_date", SortOrder.Descending),
                new ElementsParameter("teaser_image", "post_date", "summary", "url_pattern", "title")
            );

            return View(response.Items);
        }

        public async Task<ActionResult> Show(string urlSlug)
        {
            var response = await client.GetItemsAsync<Article>(
                new EqualsFilter("elements.url_pattern", urlSlug),
                new EqualsFilter("system.type", "article"),
                new DepthParameter(1)
            );

            if (response.Items.Count == 0)
            {
                throw new HttpException(404, "Not found");
            }
            else
            {
                try
                {
                    var article = response.Items[0];
                    var recommendationApiKey = ConfigurationManager.AppSettings["RecommendationApiKey"];

                    // If the recommender API key is present
                    if (!string.IsNullOrWhiteSpace(recommendationApiKey))
                    {
                        /* Get recommendations from the Recommendation engine */
                        var recommendationClient = new Kentico.Kontent.Recommender.MVC.RecommendationClient(recommendationApiKey, 5);
                        var lastMonth = TimeSpan.FromDays(30).Milliseconds;

                        var recommendedArticles = await recommendationClient
                            .CreateRequest(Request, Response, codename: article.System.Codename, limit: 2, contentType: article.System.Type)
                            //.WithFilterQuery("\"personas=Barista\" in 'properties'")
                            //.WithBoosterQuery($"if 'lastupdated' >= now() - {lastMonth} then 2 else 1")
                            .Execute();

                        var articles = (await client.GetItemsAsync<Article>(new InFilter("system.codename", recommendedArticles.Select(a => a.Codename).ToArray()))).Items;
                        article.RelatedArticles = articles.Select(a => (object)a);
                        return View(article);
                    }
                    else
                    {
                        return View(article);
                    }
                }
                catch (Exception)
                {
                    return View(response.Items[0]);
                }
            }
        }
    }
}

DancingGoat/Controllers/CafesController.cs
using DancingGoat.Models;
using Kentico.Kontent.Delivery;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace DancingGoat.Controllers
{
    public class CafesController : ControllerBase
    {
        public async Task<ActionResult> Index()
        {
            var response = await client.GetItemsAsync<Cafe>(
                new EqualsFilter("system.type", "cafe"),
                new OrderParameter("system.name")
            );
            var cafes = response.Items;

            var viewModel = new CafesViewModel
            {
                CompanyCafes = cafes.Where(c => c.Country == "USA").ToList(),
                PartnerCafes = cafes.Where(c => c.Country != "USA").ToList()
            };

            return View(viewModel);
        }
    }
}

DancingGoat/Controllers/ProductController.cs
using Kentico.Kontent.Delivery;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace DancingGoat.Controllers
{
    public class ProductController : ControllerBase
    {
        public async Task<ActionResult> Detail(string urlSlug)
        {
            var item = (await client.GetItemsAsync<object>(new EqualsFilter("elements.url_pattern", urlSlug), new InFilter("system.type", "brewer", "coffee"))).Items.FirstOrDefault();

            if (item == null)
            {
                throw new HttpException(404, "Not found");
            }
            else
            {
                ViewBag.FreeTasteRequested = TempData["formSubmited"] ?? false;
                ViewBag.UrlSlug = urlSlug;
                return View(item.GetType().Name, item);
            }
        }

        /// <summary>
        /// Dummy action.
        /// </summary>
        [HttpPost]
        public ActionResult FreeTaste()
        {
            // If needed, put your code here to work with the uploaded data in MVC.
            TempData["formSubmited"] = true;
            return RedirectToAction("Detail", new { urlSlug = Request.Form["product_url_slug"]});
        }
    }
}

DancingGoat/Views/Shared/DisplayTemplates/AboutUsViewModel.cshtml
@model DancingGoat.Models.AboutUsViewModel

@if (!string.IsNullOrEmpty(Model.OurMotto))
{
    <div class="motto">@Html.DisplayFor(vm => vm.OurMotto)</div>
}

@foreach (var video in Model.Video)
{
    @Html.DisplayFor(vm => video)
}

@Html.DisplayFor(vm => vm.FactViewModels)

DancingGoat/Views/Shared/DisplayTemplates/Article.cshtml
@using DancingGoat.Helpers.Extensions
@model DancingGoat.Models.Article

<div class="col-md-3">
    <div class="article-tile">
        <a href="@Url.Action("Show", "Articles", new { urlSlug = Model.UrlPattern })">
            @Html.AssetImage(Model.TeaserImage.FirstOrDefault(), title: $"Article {Model.Title}", cssClass: "article-tile-image", sizes: new ResponsiveImageSizes(300)
                            .WithMediaCondition(new MediaCondition { MinWidth = 330, MaxWidth = 768, ImageWidth = 468 }))
        </a>
        <div class="article-tile-date">
            @Html.DateTimeFormattedFor(vm => vm.PostDate, "M")
        </div>
        <div class="article-tile-content">
            <h2 class="h4">
                <a href="@Url.Action("Show", "Articles", new { urlSlug = Model.UrlPattern })">@Model.Title</a>
            </h2>
            <p class="article-tile-text">
                @Html.DisplayFor(vm => vm.Summary)
            </p>
        </div>
    </div>
</div>

DancingGoat/Views/Shared/DisplayTemplates/Cafe.cshtml
@model DancingGoat.Models.Cafe

<div class="col-md-6">
    <div class="cafe-tile cursor-hand js-scroll-to-map" data-address="@Model.City, @Model.Street">
        @if (ViewData.ContainsKey("ShowImage") && (bool)ViewData["ShowImage"] == true)
        {
            var photo = Model.Photo.FirstOrDefault();
            <div class="cafe-image-tile-image-wrapper" style="background-image:url('@(photo != null ? photo.Url: "")'); background-size: cover; background-position: right center;"></div>
        }
        <div class="cafe-tile-content">
            <h3 class="cafe-tile-name">@Html.DisplayFor(vm => vm.System.Name)</h3>
            <address class="cafe-tile-address">
                <a href="javascript:void(0)" class="cafe-tile-address-anchor">@Html.DisplayFor(vm => vm.Street), @Html.DisplayFor(vm => vm.City)<br />@Html.DisplayFor(vm => vm.ZipCode), @Html.DisplayFor(vm => vm.Country), @Html.DisplayFor(vm => vm.State)</a>
            </address>
            <p class="cafe-tile-phone">@Html.DisplayFor(vm => vm.Phone)</p>
        </div>
    </div>
</div>

DancingGoat/Views/Shared/DisplayTemplates/DateTime.cshtml
@model DateTime?

@{
    string keyName = nameof(DancingGoat.Helpers.Extensions.DateTimeFormatterParameters.FormatCharacter);

    if (ViewData.ContainsKey(keyName) && !string.IsNullOrEmpty(ViewData[keyName].ToString()) && Model.HasValue)
    {
        Output.Write(Model.Value.ToString(ViewData[keyName].ToString()));
    }
    else
    {
        @ViewData.TemplateInfo.FormattedModelValue
    }
}

DancingGoat/Views/Shared/DisplayTemplates/FactAboutUsViewModel.cshtml
@using DancingGoat.Helpers.Extensions
@using DancingGoat.Models
@using KenticoCloud.ContentManagement.Helpers.Models
@model DancingGoat.Models.FactAboutUsViewModel

<section class="row text-and-image">
    <h2 class="col-lg-12">
        @Model.Fact.Title
        @Html.InlineElementEditLink(
            Model.Fact.System.Language,
            Model.ParentItemElementIdentifier,
            new ElementIdentifier(Model.Fact.System.Id, FactAboutUs.TitleCodename)
            )
    </h2>
    <div class="col-md-6@( Model.Odd ? " col-md-push-6" : "" )">
          <div class="text-and-image-text@(Model.Odd ? "-right" : "" )">
              @Html.DisplayFor(vm => vm.Fact.Description)
              @Html.BlockElementEditLink(
                Model.Fact.System.Language,
                Model.ParentItemElementIdentifier,
                new ElementIdentifier(Model.Fact.System.Id, FactAboutUs.DescriptionCodename)
                )
          </div>
    </div>
    <div class="col-md-6@( Model.Odd ? " col-md-pull-6" : "" )">
        @Html.AssetImage(Model.Fact.Image.FirstOrDefault(), cssClass: "img-responsive", sizes: new ResponsiveImageSizes(300)
                            .WithMediaCondition(new MediaCondition { MinWidth = 1120, ImageWidth = 540 })
                            .WithMediaCondition(new MediaCondition { MinWidth = 768, MaxWidth = 1120, ImageWidth = 370 })
                            .WithMediaCondition(new MediaCondition { MinWidth = 330, MaxWidth = 768, ImageWidth = 468 }))
        @Html.BlockElementEditLink(
           Model.Fact.System.Language,
           Model.ParentItemElementIdentifier,
           new ElementIdentifier(Model.Fact.System.Id, FactAboutUs.ImageCodename)
           )
    </div>
</section>

DancingGoat/Views/Shared/DisplayTemplates/HostedVideo.cshtml
@model DancingGoat.Models.HostedVideo

@{ 
    var host = Model.VideoHost.FirstOrDefault()?.Codename;
    if (host == "vimeo") {
        <iframe class="hosted-video__wrapper"
                src="https://player.vimeo.com/video/@(Model.VideoId)?title =0&byline =0&portrait =0"
                width="640"
                height="360"
                frameborder="0"
                webkitallowfullscreen
                mozallowfullscreen
                allowfullscreen
                >
        </iframe>
    }
    else if (host == "youtube") {
        <iframe class="hosted-video__wrapper"
                width="560"
                height="315"
                src="https://www.youtube.com/embed/@(Model.VideoId)"
                frameborder="0"
                allowfullscreen
                >
        </iframe>
    }
}

DancingGoat/Views/Shared/DisplayTemplates/PhoneNumber.cshtml
@model string

@{
    string strippedDashes = string.IsNullOrWhiteSpace(Model) ? string.Empty : Model.Replace("-", string.Empty);
}

<a href="tel:@strippedDashes">@Model</a>

DancingGoat/Views/Shared/DisplayTemplates/Product.cshtml
@model DancingGoat.Models.IProduct

@{
    var price = Model.ProductPrice.HasValue ? Model.ProductPrice.Value.ToString("C") : "Price hasn't been set yet.";
}

<article class="product-tile">
    <a href="@Url.Action("Detail", "Product", new {urlSlug = Model.ProductUrlPattern})">
        <h1 class="product-heading">@Model.ProductProductName</h1>
        @if (Model.ProductProductStatus.Any())
        {
            <span class="product-tile-status">
                @Html.DisplayFor(vm => vm.ProductProductStatus.First().Name)
            </span>
        }
        <figure class="product-tile-image">
            @Html.AssetImage(Model.ProductImage.FirstOrDefault(), width: 452, height: 452)
        </figure>
        <div class="product-tile-info">
            <span class="product-tile-price">
                @Html.DisplayFor(vm => price)
            </span>
        </div>
    </a>
</article>

DancingGoat/Views/Shared/DisplayTemplates/RelatedArticle.cshtml
@model DancingGoat.Models.Article

<div class="col-lg-3 col-md-6 col-sm-12">
    <div class="article-tile">
        <a href="@Url.Action("Show", "Articles", new { urlslug = Model.UrlPattern })">
            @Html.AssetImage(Model.TeaserImage.FirstOrDefault(), title: "Article " + Model.Title, cssClass: "article-tile-image")
        </a>
        <div class="article-tile-date">
            @Html.DateTimeFormattedFor(vm => vm.PostDate, "M")
        </div>
        <div class="article-tile-content">
            <h2 class="h4">
                <a href="@Url.Action("Show", "Articles", new { urlslug = Model.UrlPattern})">@Html.DisplayFor(vm => vm.Title)</a>
            </h2>
            <p class="article-tile-text">
                @Html.DisplayFor(vm => vm.Summary)
            </p>
        </div>
    </div>
</div>